In [2]:
import numpy as np

In [ ]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
y = np.ones(2) # 本身就是float64类型的

In [9]:
print(X.shape)   # (3, 2)
print(X.ndim)    # 2 表示维度数
print(X.size)    # 6
print(X.dtype)
print(y.dtype)

(3, 2)
2
6
int64
float64


In [ ]:
a = np.arange(5)
print(a)
print(a.dtype)

b = np.arange(2, 8)
print(b)

c = np.arange(0,10,2)
print(c)


[0 1 2 3 4]
int64
[2 3 4 5 6 7]
[0 2 4 6 8]


In [9]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(X[0]) # 第一行
print(X[:,0]) # 第一列
print(np.mean(X,axis=0))

[1 2]
[1 3 5]
[3. 4.]


In [6]:
w = np.array([[2,1],
             [1,1]])

X @ w

array([[ 4,  3],
       [10,  7],
       [16, 11]])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
# np.linspace() 用于生成一个指定数量的等间隔数列
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 6, 8])

# 欧式距离
euclid = np.linalg.norm(a - b)
print(euclid)

euclid2 = np.sqrt(np.sum((a - b) ** 2))

7.0710678118654755


In [11]:
np.abs(-1)

np.int64(1)

In [ ]:
np.random.randn(3) # 标准的正态分布全体实数

array([ 1.78380071, -0.31801783,  0.86534547])

In [ ]:
np.random.rand(3) # 均匀分布0~1范围

array([0.58073904, 0.00967604, 0.32061041])

In [22]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
X = np.vstack([np.ones((1,len(X[0]))),X])
X

array([[1., 1.],
       [1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
A = np.array([2,4,2,7])
np.argsort(A)[:2]

array([0, 2])